# Generated by Django 5.0.4 on 2024-05-17 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PP1-PP2', 'PP1-PP2'), ('Grade1-Grade6', 'Grade1-Grade6'), ('Grade7-Grade9', 'Grade7-Grade9')], max_length=255)),
                ('level', models.CharField(choices=[('Preprimary', 'Preprimary'), ('Primary', 'Primary'), ('Junior-school', 'Junior-school')], max_length=255)),
                ('observation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Preprimary', 'Preprimary'), ('Primary', 'Primary'), ('Junior-school', 'Junior-school')], default=None, max_length=255)),
                ('principle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Administrator', 'Administrator'), ('Teacher', 'Teacher'), ('Support', 'Support')], default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('national_id_no', models.CharField(max_length=20)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_of_hiring', models.DateField()),
                ('years_of_service', models.IntegerField()),
                ('formation', models.TextField()),
                ('specialty', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GradeParallel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PP1', 'PP1'), ('PP2', 'PP2'), ('Grade1', 'Grade1'), ('Grade2', 'Grade2'), ('Grade3', 'Grade3'), ('Grade4', 'Grade4'), ('Grade5', 'Grade5'), ('Grade6', 'Grade6'), ('Grade7', 'Grade7'), ('Grade8', 'Grade8'), ('Grade9', 'Grade9')], max_length=255)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.grade')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('location', models.CharField(max_length=100)),
                ('parent_contacts', models.CharField(max_length=100)),
                ('boarder_or_day', models.CharField(choices=[('day', 'day'), ('boarder', 'boarder')], max_length=10)),
                ('means_of_transport', models.CharField(choices=[('School_bus', 'School_bus'), ('foot', 'foot'), ('motorbike', 'motorbike')], max_length=10)),
                ('route', models.CharField(max_length=100)),
                ('grade_parallel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.gradeparallel')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_metric', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('abbreviation', models.CharField(max_length=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.area')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_term', models.IntegerField()),
                ('second_term', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='exams/')),
                ('new_date_field', models.DateField(blank=True, default='YYYY-MM-DD', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.subject')),
            ],
        ),
    ]
