# Generated by Django 5.0.4 on 2024-05-17 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0002_alter_staffprofile_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='new_date_field',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_of_hiring',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
