# Generated by Django 5.0.4 on 2024-05-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0003_remove_exam_new_date_field_alter_attendance_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='years_of_service',
            field=models.IntegerField(default=0),
        ),
    ]
