# Generated by Django 5.0.4 on 2024-05-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0004_alter_staffprofile_years_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
