# Generated by Django 5.0.4 on 2024-05-18 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0006_staffprofile_name_alter_staffprofile_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='grade_parallel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myschool.gradeparallel'),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
